# Generated by Django 5.0.9 on 2026-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
