# Generated by Django 5.0.9 on 2026-09-18 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidates', models.JSONField(default=list)),
                ('recommendation', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=dict)),
                ('workload_impact', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='work.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
