# Generated by Django 5.0.9 on 2026-09-18 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0001_initial'),
        ('core', '0003_workprofile_access_needs'),
        ('work', '0002_task_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('aliases', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declared_proficiency', models.CharField(default='INTERMEDIATE', max_length=20)),
                ('observed_proficiency', models.CharField(default='UNKNOWN', max_length=20)),
                ('evidence_confidence', models.CharField(default='LOW', max_length=10)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='core.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_level', models.CharField(default='PRIMARY', max_length=12)),
                ('task_complexity', models.CharField(max_length=10)),
                ('context_tags', models.JSONField(default=list)),
                ('source', models.CharField(default='TASK_COMPLETION', max_length=30)),
                ('confirmed_by_employee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='core.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(default='REQUIRED', max_length=12)),
                ('minimum_proficiency', models.CharField(default='INTERMEDIATE', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='work.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('member', 'skill'), name='unique_employee_skill'),
        ),
        migrations.AddConstraint(
            model_name='skillevidence',
            constraint=models.UniqueConstraint(fields=('member', 'skill', 'task'), name='unique_skill_evidence'),
        ),
        migrations.AddConstraint(
            model_name='taskskillrequirement',
            constraint=models.UniqueConstraint(fields=('task', 'skill'), name='unique_task_skill'),
        ),
    ]
